# Generated by Django 5.2.6 on 2025-09-19 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_motorista', models.CharField(max_length=150, verbose_name='Nome do Motorista')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_viagem', 'Em Viagem'), ('de_folga', 'De Folga')], default='disponivel', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(default='SE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(default=2025, verbose_name='Ano')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção')], default='disponivel', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('horario_saida', models.TimeField()),
                ('data_retorno', models.DateField()),
                ('horario_retorno', models.TimeField()),
                ('passageiro1', models.CharField(max_length=150)),
                ('passageiro2', models.CharField(blank=True, max_length=150)),
                ('passageiro3', models.CharField(blank=True, max_length=150)),
                ('passageiro4', models.CharField(blank=True, max_length=150)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacao_autorizador', models.TextField(blank=True)),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('autorizador', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Gestores'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados_autorizados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_criados', to=settings.AUTH_USER_MODEL)),
                ('motorista_designado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos_site.motorista')),
                ('veiculo_designado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos_site.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(default='', max_length=200, verbose_name='Local (texto)')),
                ('ordem', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('partida', 'Partida'), ('parada', 'Parada Intermediária'), ('destino', 'Destino Final')], default='parada', max_length=20)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='veiculos_site.chamado')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('chamado', 'ordem')},
            },
        ),
    ]
