# Generated by Django 5.2.6 on 2025-09-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos_site.municipio'),
        ),
    ]
