# Generated by Django 5.2.6 on 2025-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0002_chamado_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
