# Generated by Django 5.2.6 on 2025-09-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0003_alter_parada_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parada',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='parada',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='parada',
            name='local',
            field=models.CharField(max_length=200, verbose_name='Local da Parada'),
        ),
        migrations.RemoveField(
            model_name='parada',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='tipo',
        ),
    ]
