# Generated by Django 5.2.6 on 2025-10-13 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0004_alter_parada_options_alter_parada_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='chamado',
            name='solicitante_id',
            field=models.CharField(default='sem_solicitante', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='autorizador',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Gestor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados_autorizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
