# Generated by Django 5.2.6 on 2025-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0005_remove_chamado_solicitante_chamado_solicitante_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='autorizador',
        ),
        migrations.AddField(
            model_name='chamado',
            name='autorizador_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
