# Generated by Django 5.2.6 on 2025-12-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0006_remove_chamado_autorizador_chamado_autorizador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_andamento', 'Em Andamento'), ('viagem_compartilhada', 'Viagem Compartilhada'), ('concluido', 'Concluído'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
    ]
