# Generated by Django 5.2.6 on 2025-12-12 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0007_alter_chamado_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='autorizador_id',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='solicitante_id',
        ),
        migrations.AddField(
            model_name='chamado',
            name='autorizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
