# Generated by Django 5.2.6 on 2025-12-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0008_remove_chamado_autorizador_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='viagem_compartilhada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_combinados', to='veiculos_site.chamado', verbose_name='Viagem Compartilhada'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_andamento', 'Em Andamento'), ('viagem_compartilhada', 'Viagem Compartilhada'), ('combinado', 'Combinado'), ('concluido', 'Concluído'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
    ]
