# Generated by Django 5.2.6 on 2026-01-12 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0009_chamado_viagem_compartilhada_alter_chamado_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_andamento', 'Em Andamento'), ('viagem_compartilhada', 'Viagem Compartilhada'), ('combinado', 'Combinado'), ('concluido', 'Concluído'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('chamado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='veiculos_site.chamado', verbose_name='Chamado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
