# Generated by Django 5.2.6 on 2026-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos_site', '0010_alter_chamado_status_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
